### ISSUE TITLE
Provider does not automatically pick up credentials with redirected desktop

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#111]
I've mentioned this on Slack some time ago, still happens.

On one of the laptops (Windows), even though I login with `az login`, `pulumi update` will fail to find the credentials.

The workaround is to run `robocopy "$env:userprofile\.azure" "$env:homeshare\.azure"` and then everything works, until the next logout.

I've seen this advice in [this issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/417#issuecomment-368952526) in terraform provider repo.

**Comment by lukehoban** [comment]
Looks like this is ultimately because we didn't pick up the fix in terraform-providers/terraform-provider-azurerm to pin to a newer go-homedir - https://github.com/terraform-providers/terraform-provider-azurerm/pull/1718/files.  

Fundamentally, this is because we are not locking to the precise dependencies from the upstream in our build of pulumi-azure (unlike what we do for pulumi-aws).

**Comment by joeduffy** [comment]
@pgavlin has offered to help load balance, as part of M19 shutdown. Thanks Pat!

**Comment by pgavlin** [comment]
This has been fixed with the change to use `govendor-override` to manage overrides in the `Gopkg.toml` file.
