### ISSUE TITLE
Embedding pulumi-azure into my Go application

### ISSUE THREAD

**Issue by writeameer** [pulumi/pulumi-azure#144]
Hi there,

I've just been testing out pulumi within a Go application on Azure.  Works great. I'm currently writing an application that needs to spin up/down infrastructure based on various events. Leveraging Pulumi here vs go sdk for Azure would give me all the goodness of using a regular programming language vs. json hell.

I'm wondering, however, if I can embed pulumi into my own application. At this stage, I'm running `pulumi up` or `pulumi destroy` to create/destroy Azure resources. What's the most appropriate way for me to invoke this from within a Go application ?

Thanks for any help in the right direction.

Sincerely,
Ameer Deen.

**Comment by mikhailshilkov** [comment]
@lukehoban The issue has been open for seven months without any comments. Who could help here?

**Comment by lukehoban** [comment]
Sorry for the long delay!

This is effectively the same as https://github.com/pulumi/pulumi/issues/2506, and since it’s something we would want to support in the core Pulumi model, I’ll keep that one to track this. 

In the meantime, we have also done work to expose `—json` flags on many CLI operations to ensure that scripting the CLI can be done programmatically. Today - that is still the recommended approach for automating Pulumi deployments.
