### ISSUE TITLE
Allow for 'zip deployment' and WEBSITE_RUN_FROM_PACKAGE=1

### ISSUE THREAD

**Issue by jeffhollan** [pulumi/pulumi-azure#190]
Per some recent performance work, where possible you'll get better and more consistent cold start if you use `WEBSITE_RUN_FROM_PACKAGE=1` instead of `WEBSITE_RUN_FROM_PACKAGE={blobURL}` (I'll be updating docs per [this issue](https://github.com/Azure/Azure-Functions/issues/1133) as well.

Would be good for Pulumi to allow this deployment option as well so Azure users can get the cold start benefits.  It's a bit complex only because if you are deploying a Linux based app (e.g. Python) the current method is perfect.  But if deploying against the Windows the Zip Deploy works best.  

I have [built the flow some for serverless](https://github.com/jeffhollan/components/blob/azure-functions/registry/azure-functions/src/index.js) so you can follow same logic, but in general flow is:

1. Create the app service plan
1. Create a storage account
1. Create a function app that has app settings for the storage account and `WEBSITE_RUN_FROM_PACKAGE=1`
1. Get the publishing credentials via a `POST` to the new site
1. Upload the app contents to the `zipDeploy` endpoint.  This will do the rest [per this document](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#integration-with-zip-deployment)

**Comment by lukehoban** [comment]
Thanks @jeffhollan!

Looks like currently, this would impact the code in https://github.com/pulumi/pulumi-azure-serverless/blob/master/nodejs/azure-serverless/functionApp.ts, but I’ll leave the issue here since we’re likely to pull that code over into pulumi-azure at some point soon. 

As an aside, I will note that it’s a little unfortunate the hoops you have to go through to do this, and that there is no desired-state model (i.e. pure-ARM) approach for doing this sort of thing. The equivalent is exposed in a relatively very simple desired state form in AWS, GCP, etc. any chance we’ll see pure-ARM support for deploying a zip to functions? (And app service for that matter).

**Comment by jeffhollan** [comment]
It's a valid point and I squirmed a bit while writing the issue because agree it's non-ideal.  We are tracking improvements that would allow more consistency in deployments, but couldn't speak to an ETA on when it might arrive.  Likely not in the current semester (e.g. before July 1)

**Comment by mikhailshilkov** [comment]
Azure team has made quite some improvements in the performance of external packages, so I don't think this is needed. Given that a change would be non-trivial, it's not likely we will make it any time soon, so I'm going to close this issue.

**Comment by reubano** [comment]
I think should be reopened. Using `WEBSITE_RUN_FROM_PACKAGE={blobURL}` requires anonymous access be enabled. Since [Microsoft recommends against permitting anonymous access to blob data in your storage account,](https://learn.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=portal#set-the-anonymous-access-level-for-a-container) many orgs have disabled anonymous access. This makes it impossible to load a `blobURL` (even when using a secure [SAS URL](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-sas-create-python#create-an-account-sas)). This is issue I currently face.
