### ISSUE TITLE
Add support for more Azure FunctionApp triggers.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-azure#218]
We currently support http/topic/container/queue triggers.  However, now that we're on azure functions 2.0 we can support the following as well:

1. [EventGrid triggers](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid#javascript-example)
2. [EventHub triggers](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs#trigger---javascript-example)
3. [Timer triggers](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer)

**Comment by mikhailshilkov** [comment]
+ 4. [Cosmos DB trigger](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2)

**Comment by mikhailshilkov** [comment]
So, the Event Grid trigger implementation is a bit more tricky:

1. In order to link an Event Grid subscription to an Azure Function, the webhook URL [must include a system key](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid#version-2x-runtime).

2. There is an HTTP API to get a system key, but it requires [a master key](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook#authorization-keys).

3. None of the keys are available from Pulumi resources.

4. None of the keys are available from Terraform resources: [issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/699).

5. It's not there because Azure Go SDK [doesn't support it](https://github.com/Azure/azure-sdk-for-go/issues/2397).

6. [The last comment there](https://github.com/Azure/azure-sdk-for-go/issues/2397#issuecomment-477271267) mentions that there will be a new API available soon from the Functions side.

There is an alternative path: create an HTTP-triggered function and [handle EventGrid webhook](https://github.com/Azure/azure-sdk-for-go/issues/2397#issuecomment-477271267) in manual mode: respond to validation and parse the event from HTTP request.

The downside is that we get an open HTTP function hanging around. The upside: flexibility to get events in Cloud Events standard shape.

**Comment by mikhailshilkov** [comment]
I'm watching https://github.com/Azure/azure-functions-host/issues/3994 which should simplify the implementation of the Event Grid trigger (no need to call Kudu APIs)

**Comment by mikhailshilkov** [comment]
Everything here except EventGrid is done. Closing in favor of #295.
