### ISSUE TITLE
Expose signedBlobReadUrl function

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-azure#258]
Any reason why `azure.appservice.signedBlobReadUrl` is marked as internal?

We have its copy in [several](https://github.com/pulumi/examples/blob/master/azure-ts-appservice/sas.ts#L7) [similar](https://github.com/pulumi/examples/blob/master/azure-ts-functions/sas.ts#L7) [examples](https://github.com/pulumi/examples/blob/master/azure-ts-appservice-devops/infra/sas.ts#L7) and people are probably copying it all over the place.

**Comment by lukehoban** [comment]
We should consider making it public. If we do, I assume it belongs in the storage namespace since it’s actually just about blob storage?

I do still wonder if this is the “right” way to be doing this. I am surprised there is not a Terraform data source available already to do this. A risk with the current implementation is that it uses the azure sdk in JavaScript, which in the general case won’t be using the same credentials as the Pulumi azure provider. So if we could offload this to the provider instead (via a projection of an existing Terraform dat source, or some other custom mechanism) that would seem a more robust solution.
