### ISSUE TITLE
Azure AppService Plan always computes a new name when it's Windows

### ISSUE THREAD

**Issue by w0rldart** [pulumi/pulumi-azure#316]
There's an odd issue occurring with the AppService.Plan resource, where having `kind: "windows"` forces the resource to generate a new name every time pulumi runs

Code snippet

```
const appServicePlan = new azure.appservice.Plan(`${prefix}-app-plan`, {
    kind: "windows",

    location: resourceGroup.location,
    resourceGroupName: resourceGroup.name,

    // Consumption Play
    sku: {
        size: "Y1",
        tier: "Dynamic",
    },
});
```

**Comment by lukehoban** [comment]
The newly generated name is most likely a symptom not a cause.  I assume some other aspect of the resource is marking it as needing to be replaced (which then requests a new name for the replacement).

Can you share the results of a `pulumi preview --diff` using the latest CLI version?

**Comment by stack72** [comment]
Hi @w0rldart 	

Thanks for raising the issue here. Unfortunately, you cannot use a Y1 SKU and a Windows AppService Plan. Y1 is reserved for `FunctionApp` kind as it's a dynamic tier for Function consumption

I have been able to recreate this exactly and Y1 only works when you use the following:

```
const appServicePlan = new azure.appservice.Plan(`${prefix}-app-plan`, {
    kind: "functionapp",

    location: resourceGroup.location,
    resourceGroupName: resourceGroup.name,

    // Consumption Play
    sku: {
        size: "Y1",
        tier: "Dynamic",
    },
});
```

I have also been able to confirm that I cannot choose Y1 as a SKU in the Azure console

I hope this helps

Paul
