### ISSUE TITLE
How do you add a certificate to an app service?

### ISSUE THREAD

**Issue by youngcm2** [pulumi/pulumi-azure#347]
Here is what we use in the azure cli.
upload
az webapp config ssl upload --certificate-file="$cert_path" --certificate-password=XXXXXXX --name=XXXXXXX --resource-group XXXXXXXX

bind
az webapp config ssl bind --certificate-thumbprint XXXXXXXX --name XXXXXXXX --resource-group XXXXXXXX --ssl-type "SNI"

**Comment by pgavlin** [comment]
The upstream Terraform provider does not yet support SSL certificates with App Service. The bug that tracks adding that support is here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/1136

It looks like a fix for that issue is imminent, so I would expect support for SSL certs to be added soon. In the meantime, you could try implementing a [dynamic provider](https://www.pulumi.com/docs/intro/concepts/programming-model/#dynamicproviders) to manage the certs for your app service.

**Comment by pgavlin** [comment]
(we will use the upstream issue to track adding this support)
