### ISSUE TITLE
Unable to create azure.storage.Table - plan apply fails when checking for existence

### ISSUE THREAD

**Issue by johlrich** [pulumi/pulumi-azure#360]
Pulumi makes it through the preview, but will fail to apply with an error. The error details contain a url with the resource group name instead of the storage account name in it, which I'm assuming is the problem: 

`error: Plan apply failed: Error checking for existence of existing Storage Table "table3a4db274" (Account "storageca2999c2" / Resource Group "resourcegroupa22eacc9"): tables.Client#Exists: Failure sending request: StatusCode=0 -- Original Error: Get https://resourcegroupa22eacc9.table.core.windows.net/Tables('table3a4db274'): dial tcp: lookup resourcegroupa22eacc9.table.core.windows.net: no such host`

This was reproducible on a new typescript-azure project with just a storage account + table like:

```ts
const resourceGroup = new azure.core.ResourceGroup("resourceGroup");

const account = new azure.storage.Account("storage", {
    resourceGroupName: resourceGroup.name,
    accountTier: "Standard",
    accountReplicationType: "LRS",
});

const table = new azure.storage.Table("table", {
    storageAccountName: account.name,
})
```

This is with 1.0.0

**Comment by pgavlin** [comment]
cc @mikhailshilkov @stack72

**Comment by stack72** [comment]
Hi @johlrich 	

Apologies for the problem here - I have actually fixed this in the upstream Azurerm Terraform Provider repo

https://github.com/terraform-providers/terraform-provider-azurerm/pull/4234

This will be in the next release of the Azure provider

You can follow the release of the upstream provider here - https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1340-unreleased

Paul
