### ISSUE TITLE
`resource_group_name` deprecation warnings

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-azure#392]
Trying to use `azure.appservice.HttpEventSubscription` seems to unconditionally lead to this warning:

`warning: urn:pulumi:dev::page-counter-az::azure:appservice:HttpEventSubscription$azure:storage/zipBlob:ZipBlob::site verification warning: "resource_group_name": [DEPRECATED] This field has been deprecated and is no longer used - will be removed in 2.0 of the Azure Provider`

I suspect we need to change the implementation of `HttpEventSubscription` and/or `ZipBlob` somehow?

In general, it's actually not clear to me what's changing with resource group names generally. Is there a guide somewhere on what changes should be made? Do we intend to scrub our examples also?

**Comment by mikhailshilkov** [comment]
Terraform has been gradually deprecating `resource_group_name` property in child-level resources of Azure Storage. Basically, it's not possible to put a blob into a group that is different from its storage account.

I believe `HttpEventSubscription` is fixed in master and this warning should be gone with the next release. I still need to go through all examples to see where this warning still may slip in.

**Comment by stack72** [comment]
Closed via release of v1.3.0
