### ISSUE TITLE
AccountBlobPropertiesArgs has no support for CORS

### ISSUE THREAD

**Issue by marklam** [pulumi/pulumi-azure#448]
As far as I can tell, changing the CORS settings for a storage account should be in `Pulumi.Azure.Storage.Inputs.AccountBlobPropertiesArgs` but it's missing - although they are present on `AccountQueuePropertiesArgs`.

**Comment by mikhailshilkov** [comment]
Hi @marklam, thanks for the issue.
This feature is missing in the upstream provider. I'll close the issue here to track it upstream in https://github.com/terraform-providers/terraform-provider-azurerm/issues/19. There's a PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/5425 so maybe it will be resolved soon.

**Comment by marklam** [comment]
Incidentally, after I opened this issue I realised that I can't establish the CORS rule at the time the `StorageAccount` is created, because the referring URL will be a site that is created using that StorageAccount (ie circular) reference.

**Comment by mikhailshilkov** [comment]
Yeah, you probably have to hard-code the name of either the storage account or the site to work around that
