### ISSUE TITLE
Scaling AKS defaultNodePool predicts replacing all kube resources

### ISSUE THREAD

**Issue by oliverholliday** [pulumi/pulumi-azure#467]
When trying to scale a VMSS AKS cluster's `defaultNodePool` from `2` to `3` the following preview was generated which implies it wants to replace every resource within the cluster.

It seems that it knows the `nodeCount` can be changed in-place but somehow it causes the provider to be replaced - resulting in replacing everything else.

```
Previewing update (dev2):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev2::dev2::pulumi:pulumi:Stack::dev2-dev2]
    ~ azure:containerservice/kubernetesCluster:KubernetesCluster: (update) ≡ƒöÆ
        [id=/subscriptions/REDACTED/resourcegroups/dev2/providers/Microsoft.ContainerService/managedClusters/dev2]
        [urn=urn:pulumi:dev2::dev2::azure:containerservice/kubernetesCluster:KubernetesCluster::dev2]
        [provider=urn:pulumi:dev2::dev2::pulumi:providers:azure::default_1_13_0::9d2497a2-5af9-489f-bf85-62bc01d60f3a]
      ~ defaultNodePool: {
          ~ nodeCount: 2 => 3
        }
    +-pulumi:providers:kubernetes: (replace)
        [id=189ddced-10db-4a8e-8f91-81e761cfb929]
        [urn=urn:pulumi:dev2::dev2::pulumi:providers:kubernetes::dev2]
      ~ kubeconfig: "apiVersion: v1\nclusters:\n- cluster:\n    certificate-authority-data: REDACTED\n" => output<string>
    +-kubernetes:core/v1:ServiceAccount: (replace)
        [id=default/aad-pod-id-mic-service-account]
        [urn=urn:pulumi:dev2::dev2::kubernetes:core/v1:ServiceAccount::aad-pod-id-mic-service-account]
        [provider: urn:pulumi:dev2::dev2::pulumi:providers:kubernetes::dev2::189ddced-10db-4a8e-8f91-81e761cfb929 => urn:pulumi:dev2::dev2::pulumi:providers:kubernetes::dev2::output<string>]
        apiVersion: "v1"
        kind      : "ServiceAccount"
SNIPPED REPLACING ALL OTHER KUBE RESOURCES
```

**Comment by leezen** [comment]
I believe this is because as part of changing the nodeCount from 2 to 3, you can see that the kubeconfig is marked as potentially changing. We don't know what the kubeconfig will look like as it's provider-dependent. So, conservatively, we'll mark it as changing (hence the `=> output<string>`). And because that might change, all the underlying resources might change as well. In practice, this shouldn't be the case. One way to assure yourself of this is to attempt a targeted `up` on the cluster, which shouldn't touch any of the other resources, e.g. `pulumi up --target urn:pulumi:dev2::dev2::azure:containerservice/kubernetesCluster:KubernetesCluster::dev2`

Then, you can confirm that the kubeconfig hasn't changed and doesn't require you to change the other resources via a `pulumi preview` after the targeted update has succeeded.

**Comment by oliverholliday** [comment]
Thanks I didn't know about `--target`.

**Comment by leezen** [comment]
Based on the above, I assume that helped, so closing for now. Please re-open if that wasn't the case.
