### ISSUE TITLE
Can't use same CosmosDB account on two stacks

### ISSUE THREAD

**Issue by michaelmsm89** [pulumi/pulumi-azure#483]
I seem unable to use the same CosmosDB account across two stacks with TypeScript. I created a new project from scratch to reproduce this error, with two stacks `dev` and `prod`. 

Running `pulumi stack select dev` then `pulumi up` correctly creates the Resource Group and the CosmosDB account.

Running `pulumi stack select prod` then `pulumi up` gives the error 
```
pulumi:pulumi:Stack (PulumiTest-prod):
    error: update failed

azure:cosmosdb:Account (cosmos):
    error: CosmosDB Account cd9586ea-be16-492e-99b5-3a093619cb05 already exists, please import the resource via terraform import
```

I don't want to create the CosmosDB account again for the other stack, I want to re-use it. I have created small sample files below to reproduce the error.

package.json:
```json
{
    "name": "PulumiTest",
    "devDependencies": {
        "@types/node": "^8.0.0"
    },
    "dependencies": {
        "@pulumi/pulumi": "^1.0.0",
        "@pulumi/azure": "^1.0.0"
    }
}
```

index.ts
```ts
import * as azure from '@pulumi/azure';

// Create an Azure Resource Group
const resourceGroup = new azure.core.ResourceGroup("resourceGroup", {
    name: 'test',
    location: azure.Locations.UKSouth
});

const commonArgs = {
    resourceGroupName: resourceGroup.name,
    location: resourceGroup.location,
};

const cosmosdbAccount = new azure.cosmosdb.Account("cosmos", {
    name: "cd9586ea-be16-492e-99b5-3a093619cb05",
    ...commonArgs,
    offerType: "Standard",

    consistencyPolicy: {
        consistencyLevel: "Session",
    },
    geoLocations: [{ location: resourceGroup.location, failoverPriority: 0 }],
});
```
pulumi.dev.yaml
```yml
config:
  azure:environment: public
  azure:location: uksouth
```
pulumi.prod.yaml
```yml
config:
  azure:environment: public
  azure:location: uksouth
```

**Comment by leezen** [comment]
The Pulumi programming model assumes that resources are tracked as the state for each stack. When you try to `pulumi up` the second stack, the state of the stack doesn't have a CosmosDB account. So, it attempts to create one, but the resource already exists (since it's named).

One way you can restructure your program is to use the `import` resource option [1]. A way to structure this would be to have a separate Pulumi project that represents the shared Cosmos DB resource and have it export the name of the stack. Then, in your project above import that resource via a StackReference [2].

[1] https://www.pulumi.com/docs/intro/concepts/programming-model/#import
[2] https://www.pulumi.com/docs/intro/concepts/programming-model/#stack-references

**Comment by michaelmsm89** [comment]
Thanks for the detailed explanation @leezen
