### ISSUE TITLE
Delete Before Replace not respected for Routes

### ISSUE THREAD

**Issue by jamesianberry** [pulumi/pulumi-azure#519]
Even though I have `opts = ResourceOptions(delete_before_replace=True)` set on all Routes, the following happens when I try to change the name of a Route:
```bash
pulumi up
Previewing update (dr):
     Type                       Name             Plan
     pulumi:pulumi:Stack        azure-py-vdc-dr
     └─ vdc:network:Spoke       spoke
 +      ├─ azure:network:Route  spoke-hub-r-     create
 -      └─ azure:network:Route  spoke-hub-sn-r-  delete

Resources:
    + 1 to create
    - 1 to delete
    2 changes. 45 unchanged

Do you want to perform this update? yes
Updating (dr):
     Type                       Name             Status                  Info
     pulumi:pulumi:Stack        azure-py-vdc-dr  running                 error: update failed
     └─ vdc:network:Spoke       spoke
 +      └─ azure:network:Route  spoke-hub-r-     **creating failed**     error: Error Creating/Updating Rou     
```
Details:
```bash
Changes:
 
    Type                         Name                            Operation
>   pulumi:pulumi:StackReference organization/azure-py-vdc/prod read
 
Diagnostics:
 
organization/azure-py-vdc/dr (pulumi:pulumi:Stack)
error: update failed
 
spoke-hub-r- (vdc:network:Spoke$azure:network/route:Route)
error: Error Creating/Updating Route "spoke-hub-r-c399de3f" (Route Table "spoke-sn-rt-2ba101cd" / Resource Group "dr-vdc-rg-b3d6213a"): network.RoutesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="RouteConflict" Message="Route: spoke-hub-r-c399de3f conflicts with Route: spoke-hub-sn-r-631eff02. Routes cannot have the same AddressPrefix." Details=[]
```

**Comment by lukehoban** [comment]
> Even though I have opts = ResourceOptions(delete_before_replace=True) set on all Routes, the following happens when I try to change the name of a Route

Changing the name of a resource is not a replacement, but is instead of creation of an unrelated resource and deletion of the previous resource.  This is because the name (technically the URN) of the resource is the sole notion of "identity" between resources between updates.  So there is no way for Pulumi to know that `spoke-hub-r-` and `spoke-hub-sn-r-` refer to the "same" resource.

The tool you can use to address this is `aliases`.  You can change the name but indicate that the resource was previously known by a different name (add an alias to the old name).  Pulumi will then know that although the name has changed, this is the "same" resource, and should thus be replaced (and delete-before-replaced in your case).

See https://www.pulumi.com/docs/intro/concepts/programming-model/#aliases.
