### ISSUE TITLE
SystemAssigned Identity for Cluster can't be retrieved via stack output

### ISSUE THREAD

**Issue by elsesiy** [pulumi/pulumi-azure#530]
Hi @mikhailshilkov,

I'm using `3.1.0` which should support exposing the cluster and kubelet identities but I'm receiving a panic while trying to run this:

`ctx.Export("kubeIdentity", k8scluster.Identity.PrincipalId())`

Error:
```
error: an unhandled error occurred: program exited with non-zero exit code: 1

panic: applier must have 1 input parameter assignable from *containerservice.KubernetesClusterIdentity

```

I reported this a while back to @lukehoban via Slack, not sure if this has been tracked somewhere else already.

Thanks guys!

**Comment by lukehoban** [comment]
I swore we had an issue open already on this (and that we had fixed it!). But I can’t find it right now. 

The issue is that this generated function in the SDK is wrong - it should take a pointer as mentioned in the error message:

```

// The principal id of the system assigned identity which is used by master components.
func (o KubernetesClusterIdentityPtrOutput) PrincipalId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v KubernetesClusterIdentity) *string { return v.PrincipalId }).(pulumi.StringPtrOutput)
}
```

Note that this should be easy to workaround. Y just using `.ApplyT` or `.ApplyString` yourself instead of this `.PrincipalId()` helper method. 

But we definitely need to fix this.
