### ISSUE TITLE
Sensitive `ARM_` env vars get serialized into state file (and in plain text)

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-azure#576]
Sensitive ARM env vars like `ARM_CLIENT_SECRET` will currently get picked up from the environment and stored into the statefile in plain text.  Two issues:
1. It is not clear these (and even some of the non-sensitive env var) belong in the state in the first place
2. If they do need to be in the state, they should be marked as secret and thus encrypted by default

**Comment by lukehoban** [comment]
FWIW - A similar things came up in https://github.com/pulumi/pulumi-aws/pull/894.

**Comment by carterwilliamson** [comment]
Additionally, I think not storing default provider credentials in state is the correct path.

We had this case last month:
- We built a stack
- Updated the SP secret 
- Tried to destroy the stack with `pulumi destroy --refresh` (--refresh makes sure our delete doesn't fail due to already deleted resources), this failed because the refresh tried to use existing credentials in a provider

We had to work around this by running `pulumi up --target <provider urn>`, then running `pulumi destroy --refresh`

**Comment by carterwilliamson** [comment]
Looks like this may have been a red-herring. We might have a duplicated provider that is "inheriting" the default provider's values, this is where the secrets get written into state.

It seems like if you had:
```python
second_provider = pulumi_azure.Provider(subscription_id=<>) # Client details not specified.
```

This should by-default encrypt or not store the client details.

I would go as far as to argue the client details should _never_ be stored in the stack, but I'm open to reasons why that's a good idea.
