### ISSUE TITLE
azure.storage.getAccount() seems to accept the wrong input type

### ISSUE THREAD

**Issue by farzadmf** [pulumi/pulumi-azure#594]
Hi, I have the following code:
```typescript
const groupName = azure.core.getResourceGroup({
  name: 'myrg',
}).then(rg => rg.name);

const account = azure.storage.getAccount({
  name: 'fmajidfayyaz',
  resourceGroupName: groupName,
});
```

However, I see an error saying that: `Type 'Promise<string>' is not assignable to type 'string'`. This seems to be because `azure.storage.getAccount()` is accepting `resourceGroupName` as `string?`.

If I go into the type definitions and change the input type to be `pulumi.Input<string>`, it seems to solve the issue

**Comment by leezen** [comment]
This is because the `get` calls expect prompt values (as opposed to an `Input` which can be a `Promise` or `Output` in addition to prompt). You probably actually do want to use this as a `Promise`:

```typescript
const account = azure.core.getResourceGroup({
  name: 'myrg',
}).then(rg => azure.storage.getAccount({
  name: 'fmajidfayyaz',
  resourceGroupName: rg.name,
});
```

Optionally, if you prefer to write everything in `async/await` syntax, you can make your top-level  an async entrypoint by following the description [here](https://www.pulumi.com/docs/intro/languages/javascript/#entrypoint) around exporting a top-level async function.

This would allow you to write the above like:

```typescript
const groupName = await azure.core.getResourceGroup({
  name: 'myrg',
}).then(rg => rg.name);

const account = await azure.storage.getAccount({
  name: 'fmajidfayyaz',
  resourceGroupName: groupName,
});

// ...
```

**Comment by farzadmf** [comment]
Thank you @leezen for your answer (I'm all over your GitHub repos 😄 )

That's super cool @leezen that there's support for `async/await`; I'll definitely try it out
