### ISSUE TITLE
Specifying SQL Server PublicNetworkAccessEnabled

### ISSUE THREAD

**Issue by CalumJEadie** [pulumi/pulumi-azure#608]
I would like to be able to write code like the following

```csharp
new SqlServer("sql-server", new SqlServerArgs
{
    PublicNetworkAccessEnabled = false
});
```

`PublicNetworkAccessEnabled` is a property available in a SQL Server ARM Template and seems to be available in the [Pulumi NodeJS provider](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/azure/mssql/#Server-publicNetworkAccessEnabled).

I'm new to Pulumi so I don't know if this is a bug, missing feature or more to be expected that the C# API would not cover all properties.

I would be grateful for advice on how to workaround. Is that something that Pulumi would take on adding? Can users of Pulumi add this sort of thing in and how quickly can changes like that be integrated? I'm aware Pulumi has open source components but not about how to contribute.

Thanks!

**Comment by leezen** [comment]
When I look at the C# documentation, it seems to be there? 

https://www.pulumi.com/docs/reference/pkg/dotnet/Pulumi.Azure/Pulumi.Azure.MSSql.ServerArgs.html#Pulumi_Azure_MSSql_ServerArgs_PublicNetworkAccessEnabled

I think the issue is you're trying to use `SqlServerArgs` (which comes from `Pulumi.Azure.Sql`) vs. `Pulumi.Azure.MSSql.ServerArgs`

`PublicNetworkAccessEnabled` doesn't appear to be a property for SQL Server in any of the languages
