### ISSUE TITLE
Azure-python - failed building wheel for pulumi-azure 

### ISSUE THREAD

**Issue by szymonbr** [pulumi/pulumi-azure#616]
I'm facing an issue while attempting to create a **pulumi project** from `azure-python` template at my debian based WSL2 with the following error message:
```
Building wheels for collected packages: pulumi-azure
  Running setup.py bdist_wheel for pulumi-azure ... error
  Complete output from command /home/user/projects/pulumi-lab/quickstart/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-0lf_o1d0/pulumi-azure/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-pi2xt5kd --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pulumi-azure
  Running setup.py clean for pulumi-azure
Failed to build pulumi-azure
Installing collected packages: six, grpcio, protobuf, dill, pulumi, attrs, arpeggio, parver, semver, pulumi-azure
  Running setup.py install for pulumi-azure ... done
Successfully installed arpeggio-1.9.2 attrs-19.3.0 dill-0.3.2 grpcio-1.29.0 parver-0.3.0 protobuf-3.12.2 pulumi-2.4.0 pulumi-azure-3.10.0 semver-2.10.2 six-1.15.0
Finished installing dependencies

Your new project is ready to go! 
```
As a workaround I create `venv` first and then initialize the project with `--force` option.

However, I would rather fix it and not add additional, manual steps for creating new projects. 

First of all I'm a little bit lost with output of pulumi command because despite the error is raised creating the project is completed and it's been reported that I were ready to go. I'm not sure if I may safely ignore such error. 
In case I shouldn't maybe somebody could have an idea what's wrong when `pulumi` attempts to initialize `python venv`. Is it something wrong with my local python setup or with pulumi?

**Comment by justinvp** [comment]
Thanks for reporting this, @szymonbr, and sorry for the trouble.

I would have expected the `pulumi new` command to fail if the "install dependencies" step fails. Were you able to actually run the program afterwards (e.g. `pulumi up`), or was it just confusing to see errors in the `pulumi new` output when it otherwise succeeded?

In any case, it looks like the reason for the underlying error is because `wheel` isn't installed. I think we're going to want to fix Pulumi to run `venv/bin/python -m pip install --upgrade pip setuptools wheel` before running `venv/bin/python -m pip install -r requirements.txt` to ensure `pip`, `setuptool`, and `wheel` are installed and up-to-date inside the virtual environment. We're tracking this in https://github.com/pulumi/pulumi/issues/4810, so I'm going to close this as a duplicate.
