### ISSUE TITLE
import_ keyword for pulumi_azure.apimanagement.Api no longer works

### ISSUE THREAD

**Issue by sindre-nistad** [pulumi/pulumi-azure#658]
Hi,

When using the `pulumi_azure` Python package, version 3.14.0, I get an error message when creating a `pulumi_azure.apimanagement.Api`, with the `import_` key word;

```
  azure:apimanagement:Api (<resource name>):
    error: azure:apimanagement/api:Api resource '<resource name>' has a problem: : invalid or unknown key: import_
```

This key (used to specify the content of an OpenAPI specification), is described in the included documentation, and worked fine in version 3.11.0.

I've searched for information on whether `import_` was deprecated, but I didn't find any mention of that.

**Comment by komalali** [comment]
Yikes, this is unfortunate. I traced this back to https://github.com/pulumi/pulumi/pull/4895 which resulted in `import_` being removed from the casing tables. https://github.com/pulumi/pulumi-azure/commit/2b1e120ba583669817b2e7f8dd62d8ffe0d65140#diff-ab1cf52803ef93742c9a0b61d0f9aaf5L454

@lblackstone I think we need to include the single word properties in the casing tables since they are protected keywords in python. I believe the fix here is to revert https://github.com/pulumi/pulumi/pull/4895
