### ISSUE TITLE
Why are "Args" classes sealed?

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/pulumi-azure#713]
I would like to inherit from the "Args" classes as a means of setting default values, such as:

```csharp
    public class FunctionAppArgsWrapper : FunctionAppArgs
    {
        public FunctionAppArgsWrapper()
        {
            HttpsOnly = true;
        }
    }
```

Unfortunately, these classes are `sealed`, and, therefore, the wrapper cannot be accomplished.

Do the "Args" classes need to be marked `sealed`? What is the recommended practice for setting custom settings? In particular, I'd like to share these defaults via a NuGet package.

**Comment by mikhailshilkov** [comment]
I believe it is a common design principle for .NET libraries: seal a class unless it's deliberately and carefully designed to be extensible.

If a class is unsealed, there are more ways to introduce breaking changes, since someone might have subclassed it and depend on all kinds of its behavior. It may also lead to confusion if somebody extends the args with extra properties and expects them to be set on the resource.

You could have a factory or a bulder to produce instances of an args class. A very simplistic example:

```cs
public static class ArgsFactory
{
    public static FunctionAppArgs MakeAwesomeFunctionAppArgs(string planId)
    {
        return new FunctionAppArgs
        {
            PlanId = planId,
            // all other props
        };
    }
}
