### ISSUE TITLE
Cannot delete "default" node pool on Kubernetes

### ISSUE THREAD

**Issue by lbargery** [pulumi/pulumi-azure#732]
I created a Kubernetes cluster using Pulumi a while back and so made a default node pool with 2 VMs which were of medium size. I now want to increase both the size and number of VMs I'm using.

```
var defaultNodePool = new KubernetesClusterDefaultNodePoolArgs
            {
                Name = "aksagentpool",
                NodeCount = 2,
                VmSize = "Standard_F2s_v2",
                OsDiskSizeGb = 100,
                VnetSubnetId = builderWithNetwork.Network.ServiceSubnet.Id,
                EnableNodePublicIp = false,
                OrchestratorVersion = "1.17.9",
                Type = "VirtualMachineScaleSets",
                MaxPods = 30,
            };

var cluster = new KubernetesCluster($"{context.StackName}-aks", new KubernetesClusterArgs
            {
                DefaultNodePool = defaultNodePool,
...
```

To do this, I've created an extra node pool and referenced the cluster like below:

```
var extraNodeSet = new KubernetesClusterNodePool("aks-nodepool", new KubernetesClusterNodePoolArgs()
                {
                    Name = "aksnodepool",
                    NodeCount = 3,
                    AvailabilityZones = new []{"1", "2", "3"},
                    VmSize = "Standard_F8s_v2",
                    OsDiskSizeGb = 100,
                    VnetSubnetId = builderWithNetwork.Network.ServiceSubnet.Id,
                    EnableNodePublicIp = false,
                    OrchestratorVersion = "1.17.9",
                    MaxPods = 30,
                    OsType = "Linux",
                    KubernetesClusterId = cluster.Id,
                });
```

However. I now want to get rid of my initial "default" node pool. It doesn't seem like I can change the default node pool at all, this leads to a "replace" operation on the cluster which I definitely don't want.

I did think I could delete the original node pool in the Azure portal and do a refresh to see what happened but this felt pretty overkill.

**Comment by viveklak** [comment]
@lbargery sadly it appears to be a limitation as implemented in terraform - see https://github.com/terraform-providers/terraform-provider-azurerm/issues/7093.

That said, the following should work:
1. create a new `system` (`Mode: "System"`) nodepool in Pulumi with the desired size
1. delete the default nodepool from the Azure console
1. `pulumi refresh`

Note that subsequent refreshes will construe the new nodepool's configurations as the default nodepool. I will have to check if that is expected behavior. However, the desired nodepool shape and size can be achieved using the above hack. 

Apologies for the inconvenience.

**Comment by lbargery** [comment]
Got it - thanks. Have made this work for now.

**Comment by viveklak** [comment]
Thanks for the update @lbargery. I will close this for now but please reopen if you run into issues.
